name: "Build Mod"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build Mod"
        uses: geode-sdk/build-geode-mod@main
        with:
          # This specific combination usually bypasses the platform error
          target: "Android"
          build-config: "Release"
          combine: true
