name: "Build Mod"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build Mod"
        uses: geode-sdk/build-geode-mod@main
        with:
          # Changing this to a list format ensures the action 
          # passes the --platform flag correctly to the CLI.
          platforms: "android"
          combine: true
