name: Build Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: geode-sdk/build-geode
-mod@main
        with:
          target: Android
